apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoisync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoisync
  template:
    metadata:
      labels:
        app: invoisync
    spec:
      containers:
        - name: invoisync
          image: invoisyncregistry.azurecr.io/invoisync:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "invoisync-server.postgres.database.azure.com"
            - name: DATABASE_USER
              value: "weeklymagpie3"
            - name: DATABASE_PASSWORD
              value: "5pdYL7gWd2T05MpLAO3_Ug"
            - name: DATABASE_NAME
              value: "invoisync"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - invoisync
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: invoisync-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: invoisync
